[theme]
primaryColor="#2563eb"
backgroundColor="#f3f4f6"
secondaryBackgroundColor="#ffffff"
textColor="#1f2937"
font="sans serif"

[server]
maxUploadSize=50
enableXsrfProtection=true

[browser]
gatherUsageStats=false